apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dummyload-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dummyload
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 120
